# Formerly called: anthropic_filemap.yaml
# This template is heavily inspired by anthropic's computer use demo, but you can use
# it with any LM.
agent:
  templates:
    system_template: |-
      You are operating as and within SWE-agent, a CLI coding-agent running locally. It wraps open source LLMs to enable natural language interaction with a local codebase. Use the available tools when helpful.

      You can:

      Receive user prompts, project context, and files.
      Send responses and emit function calls (e.g., shell commands, code edits).
      Apply patches, run commands, based on user approvals.
      Answer the user's request using the relevant tool(s), if they are available. Check that all the required parameters for each tool call are provided or can reasonably be inferred from context. IF there are no relevant tools or there are missing values for required parameters, ask the user to supply these values; otherwise proceed with the tool calls. If the user provides a specific value for a parameter (for example provided in quotes), make sure to use that value EXACTLY. DO NOT make up values for or ask about optional parameters. Carefully analyze descriptive terms in the request as they may indicate required parameter values that should be included even if not explicitly quoted.

      Act as an agentic assistant, if a user asks for a long task, break it down and do it step by step.
    instance_template: |-
      <uploaded_files>
      {{working_dir}}
      </uploaded_files>
      I've uploaded a python code repository in the directory {{working_dir}}. Consider the following PR description:

      <pr_description>
      {{problem_statement}}
      </pr_description>

      Can you help me implement the necessary changes to the repository so that the requirements specified in the <pr_description> are met?
      If you write tests depending on a server running, make sure to start the server in a background process so it won't timeout the console.

      1. As a first step, it might be a good idea to find and read code relevant to the <pr_description>
      2. Create a script to test the error or feature and execute it with `python <filename.py>` using the bash tool, to confirm unsuccessful test.
      3. Edit the sourcecode of the repo to resolve the issue
      4. Rerun your reproduce script and confirm that the error is fixed!
      5. Think about edgecases and make sure your fix handles them as well
      Your thinking should be thorough and so it's fine if it's very long.

      If you need to start a command that has long-running output (e.g. a web server or installing dependencies with npm or pip), you should _always_ use the following pattern:
      server_command &> my_server_log.txt &

      This way you can see the server's output in the my_server_log.txt file and it will not block the rest of your work.
    next_step_template: |-
      OBSERVATION:
      {{observation}}
    next_step_no_output_template: |-
      Your command ran successfully and did not produce any output.
  tools:
    env_variables:
      PAGER: cat
      MANPAGER: cat
      LESS: -R
      PIP_PROGRESS_BAR: 'off'
      TQDM_DISABLE: '1'
      GIT_PAGER: cat
    bundles:
      - path: tools/filemap
      - path: tools/registry
      - path: tools/edit_anthropic
      - path: tools/review_on_submit_m
      # - path: tools/image_tools  # lets models view image files
      # - path: tools/web_browser  # browser tool for interacting with web servers
    registry_variables:
      USE_FILEMAP: 'True'
      USE_LINTER: 'True'
      SUBMIT_REVIEW_MESSAGES:
        - |
          Thank you for your work on this issue. Please carefully follow the steps below to help review your changes.

          1. If you made any changes to your code after running the reproduction script, please run the reproduction script again.
            If the reproduction script is failing, please revisit your changes and make sure they are correct.
            If you have already removed your reproduction script, please ignore this step.
          2. Remove your reproduction script and other temporary files (if you haven't done so already).
          4. Run the submit command again to confirm.

          Here is a list of all of your changes:

          <diff>
          {{diff}}
          </diff>
    enable_bash_tool: true
    parse_function:
      type: function_calling
  # history_processors:
    # - type: image_parsing  # parses base64 encoded images in the observation
    # - type: cache_control
    #   last_n_messages: 5
  model:
    # temperature: 1.
    name: openai/mistralai/devstral-small-2-2512
    api_key: sk-unk
    api_base: http://hal-8999:12345/v1
    per_instance_cost_limit: 0
    total_cost_limit: 0
    completion_kwargs:
      timeout: 1800
      # reasoning_effort: high
      # allowed_openai_params:
      #   - reasoning_effort
      parallel_tool_calls: True
    per_instance_call_limit: 0
    # max_input_tokens: 40960
    litellm_model_registry: "./models.json"

env:
  post_startup_commands:
    - pip install -e .[dev]
  # repo:
    # path: ./
  #   base_commit: swe-agent-fix-#20-95384112
  deployment:
    image: kavai/swe-agent
actions:
  # apply_patch_locally: True
  open_pr: True
  pr_config:
    skip_if_commits_reference_issue: False
# problem_statement:
#   text: The last commit was successful in adding new functionality, but it removed the run details/chat output. Make sure that everything works for the web+api as expected. Remove unneeded files.